export const contentEN = {
    title: 'Form',
    errorPatientRequired: 'Please use a valid patient',
    errorPhysicianRequired: 'Please use a valid physician',
    errorInvalidTime: 'Invalid time format',
    labelPatient: 'Patient',
    labelPhysician: 'Physician',
    labelDate: 'Appointment date',
    labelTime: 'Time',
    labelNotes: 'Notes',
    placeholderPatient: 'Select patient by name',
    placeholderPhysician: 'Select physician by name',
    textNoCommandPatientFound: 'No patient found',
    textNoCommandPhysicianFound: 'No physician found',
    placeholderTime: 'Select a time slot',
    textToastSuccess: 'Appointment add successfully',
    textToastFail: 'Failed to add appointment',
    textButtonSend: 'Add appointment',
    textButtonSending: 'Sending',
}

export type AddNewAppointmentFormContent = typeof contentEN

export const contentES: AddNewAppointmentFormContent = {
    title: 'Formulario',
    errorPatientRequired: 'Por favor, seleccione un paciente válido',
    errorPhysicianRequired: 'Por favor, seleccione un médico válido',
    errorInvalidTime: 'Formato de hora no válido',
    labelPatient: 'Paciente',
    labelPhysician: 'Médico',
    labelDate: 'Fecha de la cita',
    labelTime: 'Hora',
    labelNotes: 'Notas',
    placeholderPatient: 'Seleccionar paciente por nombre',
    placeholderPhysician: 'Seleccionar médico por nombre',
    textNoCommandPatientFound: 'No se encontró ningún paciente',
    textNoCommandPhysicianFound: 'No se encontró ningún médico',
    placeholderTime: 'Seleccionar un horario disponible',
    textToastSuccess: 'Cita añadida correctamente',
    textToastFail: 'Error al añadir la cita',
    textButtonSend: 'Añadir cita',
    textButtonSending: 'Enviando',
}
