export const contentEN = {
    title: 'Register Practitioner',
    labelFirstName: 'First Name',
    labelLastName: 'Last Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelBirthDate: 'Birth Date',
    labelGender: 'Gender',
    labelRole: 'Role',
    labelAvailableTime: 'Available Time',
    labelDaysOfWeek: 'Day',
    labelStartTime: 'Start',
    labelEndTime: 'End',
    labelLocation: 'Location',
    labelSpecialty: 'Specialty',
    textButtonSend: 'Register Practitioner',
    textButtonSending: 'Registering...',
    textButtonAddTime: 'Add time slot',
    textToastSuccess: 'Practitioner registered successfully',
    textToastFail: 'Failed to register practitioner',
    errorNoAccessPolicy: 'Access policy not found for role',
}

export type AddNewPractitionerFormContent = typeof contentEN

export const contentES: AddNewPractitionerFormContent = {
    title: 'Registrar profesional',
    labelFirstName: 'Nombre',
    labelLastName: 'Apellido',
    labelEmail: 'Correo electrónico',
    labelPhone: 'Teléfono',
    labelBirthDate: 'Fecha de nacimiento',
    labelGender: 'Género',
    labelRole: 'Rol',
    labelAvailableTime: 'Horario disponible',
    labelDaysOfWeek: 'Día',
    labelStartTime: 'Inicio',
    labelEndTime: 'Fin',
    labelLocation: 'Ubicación',
    labelSpecialty: 'Especialidad',
    textButtonSend: 'Registrar profesional',
    textButtonSending: 'Registrando...',
    textButtonAddTime: 'Añadir franja horaria',
    textToastSuccess: 'Profesional registrado correctamente',
    textToastFail: 'Error al registrar el profesional',
    errorNoAccessPolicy: 'Política de acceso no encontrada para el rol',
}
