export const contentEN = {
    male: 'Male',
    female: 'Female',
    other: 'Other',
    unknown: 'Unknown',
    annulled: 'Annulled',
    divorced: 'Divorced',
    interlocutory: 'Interlocutory',
    legallySeparated: 'Legally Separated',
    married: 'Married',
    polygamous: 'Polygamous',
    neverMarried: 'Never Married',
    domesticPartner: 'Domestic Partner',
    unmarried: 'Unmarried',
    widowed: 'Widowed',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    father: 'Father',
    mother: 'Mother',
    brother: 'Brother',
    sister: 'Sister',
    grandfather: 'Grandfather',
    grandmother: 'Grandmother',
    son: 'Son',
    daughter: 'Daughter',
    uncle: 'Uncle',
    aunt: 'Aunt',
    halfBrother: 'Half-brother',
    halfSister: 'Half-sister',
    partial: 'Partial',
    completed: 'Completed',
    enteredInError: 'Entered in error',
    healthUnknown: 'Health unknown',
}

export type ValueSetsContent = typeof contentEN

export const contentES: ValueSetsContent = {
    male: 'Hombre',
    female: 'Mujer',
    other: 'Otro',
    unknown: 'Desconocido',
    annulled: 'Anulado',
    divorced: 'Divorciado',
    interlocutory: 'Interlocutorio',
    legallySeparated: 'Separado legalmente',
    married: 'Casado',
    polygamous: 'Polígamo',
    neverMarried: 'Nunca casado',
    domesticPartner: 'Pareja de hecho',
    unmarried: 'Soltero',
    widowed: 'Viudo',
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sábado',
    sunday: 'Domingo',
    father: 'Padre',
    mother: 'Madre',
    brother: 'Hermano',
    sister: 'Hermana',
    grandfather: 'Abuelo',
    grandmother: 'Abuela',
    son: 'Hijo',
    daughter: 'Hija',
    uncle: 'Tío',
    aunt: 'Tía',
    halfBrother: 'Medio hermano',
    halfSister: 'Media hermana',
    partial: 'Parcial',
    completed: 'Completado',
    enteredInError: 'Ingresado por error',
    healthUnknown: 'Estado de salud desconocido',
}
