import { APP_FHIR_BASE_URL } from '@shared/fhir/config'

const COMMUNICATION_TAG_SYSTEM = `${APP_FHIR_BASE_URL}/tags`
const COMMUNICATION_TAG_CODE = 'internal-announcement'
const COMMUNICATION_CATEGORY_SYSTEM =
    `${APP_FHIR_BASE_URL}/communication-category`
const COMMUNICATION_CATEGORY_CODE = 'clinic-announcement'

export {
    COMMUNICATION_TAG_SYSTEM,
    COMMUNICATION_TAG_CODE,
    COMMUNICATION_CATEGORY_SYSTEM,
    COMMUNICATION_CATEGORY_CODE,
}
