export const contentEN = {
    labelDescription: 'Description',
    labelExamination: 'Examination',
    labelWeight: 'Weight',
    labelHeight: 'Height',
    textGeneral: 'General',
    textVitals: 'Vitals',
    textBiologicalBasic: 'Biological Basics',
    temperature: 'Temperature',
    pas: 'Systolic Blood Pressure',
    pad: 'Diastolic Blood Pressure',
    fc: 'Heart Rate',
    fr: 'Respiratory Rate',
    oximetry: 'Oxygen Saturation',
    eating: 'Eating',
    thirst: 'Thirst',
    urine: 'Urine',
    feces: 'Feces',
    sleep: 'Sleep',
    mood: 'Mood',
}

export type ObservationTabContent = typeof contentEN

export const contentES: ObservationTabContent = {
    labelDescription: 'Descripción',
    labelExamination: 'Exploración',
    labelWeight: 'Peso',
    labelHeight: 'Talla',
    textGeneral: 'General',
    textVitals: 'Signos vitales',
    textBiologicalBasic: 'Datos biológicos básicos',
    temperature: 'Temperatura',
    pas: 'Presión arterial sistólica',
    pad: 'Presión arterial diastólica',
    fc: 'Frecuencia cardíaca',
    fr: 'Frecuencia respiratoria',
    oximetry: 'Saturación de oxígeno',
    eating: 'Alimentación',
    thirst: 'Sed',
    urine: 'Orina',
    feces: 'Heces',
    sleep: 'Sueño',
    mood: 'Estado de ánimo',
}
