export const contentEN = {
    title: 'Register patient',
    errorUserNameTooShort: 'The username must be at least 3 characters long',
    errorUserNameTooLong: 'The username cannot be longer than 20 characters',
    errorUserNameDisallowedCharacters: 'Only letters, numbers, and underscores',
    errorUserLastNameTooShort:
        'The username must be at least 3 characters long',
    errorUserLastNameTooLong:
        'The username cannot be longer than 20 characters',
    errorUserLastNameDisallowedCharacters:
        'Only letters, numbers, and underscores',
    errorEmailInvalid: 'Please use a valid email address',
    errorEmailRequired: 'The email address is required',
    errorPasswordNoMatch: 'Passwords do not match',
    errorUserDniTooShort: 'DNI to short',
    errorUserDniTooLong: 'DNI too long',
    errorUserDniLength: 'DNI has to be 8 digits without letter',
    errorUserDniInvalidFormat: 'Invalid DNI format',
    errorGenderRequired: 'Please select a gender',
    errorBirthDateRequired: 'Please select a birth date',
    errorBirthDateFuture: 'This is imposible',
    errorBirthDateTooOld: 'Too old',
    errorPhoneInvalid: 'Phone invalid',
    errorMaritalStatusRequired: 'Please select a marital status',
    labelUserName: 'Name',
    labelUserLastName: 'Last Name',
    labelDNI: 'DNI',
    labelEmail: 'Email',
    labelGender: 'Select gender',
    labelPhone: 'Phone',
    labelBirthday: 'Birthday',
    labelBirthplace: 'Birthplace',
    labelPlaceOfResidence: 'Place of Residence',
    labelOccupation: 'Occupation',
    textButtonSend: 'Register new',
    textButtonSending: 'Sending',
    textToastSuccess: 'Register patient successfully',
    textToastFail: 'Failed to register patient',
}

export type AddNewPatientContent = typeof contentEN

export const contentES: AddNewPatientContent = {
    title: 'Registrar paciente',
    errorUserNameTooShort: 'El nombre debe tener al menos 3 caracteres',
    errorUserNameTooLong: 'El nombre no puede tener más de 20 caracteres',
    errorUserNameDisallowedCharacters: 'Solo letras, números y guiones bajos',
    errorUserLastNameTooShort:
        'El apellido debe tener al menos 3 caracteres',
    errorUserLastNameTooLong:
        'El apellido no puede tener más de 20 caracteres',
    errorUserLastNameDisallowedCharacters:
        'Solo letras, números y guiones bajos',
    errorEmailInvalid: 'Por favor, introduzca una dirección de correo válida',
    errorEmailRequired: 'La dirección de correo es obligatoria',
    errorPasswordNoMatch: 'Las contraseñas no coinciden',
    errorUserDniTooShort: 'DNI demasiado corto',
    errorUserDniTooLong: 'DNI demasiado largo',
    errorUserDniLength: 'El DNI debe tener 8 dígitos sin letra',
    errorUserDniInvalidFormat: 'Formato de DNI no válido',
    errorGenderRequired: 'Por favor, seleccione un sexo',
    errorBirthDateRequired: 'Por favor, seleccione una fecha de nacimiento',
    errorBirthDateFuture: 'Esto es imposible',
    errorBirthDateTooOld: 'Demasiado mayor',
    errorPhoneInvalid: 'Teléfono no válido',
    errorMaritalStatusRequired: 'Por favor, seleccione un estado civil',
    labelUserName: 'Nombre',
    labelUserLastName: 'Apellido',
    labelDNI: 'DNI',
    labelEmail: 'Correo electrónico',
    labelGender: 'Seleccionar sexo',
    labelPhone: 'Teléfono',
    labelBirthday: 'Fecha de nacimiento',
    labelBirthplace: 'Lugar de nacimiento',
    labelPlaceOfResidence: 'Lugar de residencia',
    labelOccupation: 'Ocupación',
    textButtonSend: 'Registrar nuevo',
    textButtonSending: 'Enviando',
    textToastSuccess: 'Paciente registrado correctamente',
    textToastFail: 'Error al registrar el paciente',
}
