const content = {
    title: 'Register patient',
    errorUserNameTooShort: 'The username must be at least 3 characters long',
    errorUserNameTooLong: 'The username cannot be longer than 20 characters',
    errorUserNameDisallowedCharacters: 'Only letters, numbers, and underscores',
    errorUserLastNameTooShort:
        'The username must be at least 3 characters long',
    errorUserLastNameTooLong:
        'The username cannot be longer than 20 characters',
    errorUserLastNameDisallowedCharacters:
        'Only letters, numbers, and underscores',
    errorEmailInvalid: 'Please use a valid email address',
    errorEmailRequired: 'The email address is required',
    errorPasswordNoMatch: 'Passwords do not match',
    errorUserDniTooShort: 'DNI to short',
    errorUserDniTooLong: 'DNI too long',
    errorUserDniLength: 'DNI has to be 8 digits without letter',
    errorUserDniInvalidFormat: 'Invalid DNI format',
    errorGenderRequired: 'Please select a gender',
    errorBirthDateRequired: 'Please select a birth date',
    errorBirthDateFuture: 'This is imposible',
    errorBirthDateTooOld: 'Too old',
    errorPhoneInvalid: 'Phone invalid',
    errorMaritalStatusRequired: 'Please select a marital status',
    labelUserName: 'Name',
    labelUserLastName: 'Last Name',
    labelDNI: 'DNI',
    labelEmail: 'Email',
    labelGender: 'Select gender',
    labelPhone: 'Phone',
    labelBirthday: 'Birthday',
    labelBirthplace: 'Birthplace',
    labelPlaceOfResidence: 'Place of Residence',
    labelOccupation: 'Occupation',
    textButtonSend: 'Register new',
    textButtonSending: 'Sending',
    textToastSuccess: 'Register patient successfully',
    textToastFail: 'Failed to register patient',
}

export default content
