const content = {
    labelNoKnownFamilyHistory: 'No known family history',
    descriptionNoKnownFamilyHistory:
        'Toggle if the patient has no known family history of disorder',
    labelRelationship: 'Relationship',
    labelCondition: 'Condition',
    labelStatus: 'Status',
    labelDeceased: 'Deceased',
    descriptionDeceased: 'Has this family member passed away?',
    labelNote: 'Note',
    placeholderCondition: 'e.g. Diabetes mellitus tipo 2',
    placeholderNote: 'Additional notes...',
    placeholderSelect: 'Select...',
    textButtonSave: 'Save',
    textButtonSaving: 'Saving...',
    textToastSuccess: 'Family member history saved successfully',
    textToastFail: 'Failed to save family member history',
    relationshipOptions: [
        { label: 'Father', value: 'FTH' },
        { label: 'Mother', value: 'MTH' },
        { label: 'Brother', value: 'BRO' },
        { label: 'Sister', value: 'SIS' },
        { label: 'Grandfather', value: 'GRFTH' },
        { label: 'Grandmother', value: 'GRMTH' },
        { label: 'Son', value: 'SON' },
        { label: 'Daughter', value: 'DAU' },
        { label: 'Uncle', value: 'UNCLE' },
        { label: 'Aunt', value: 'AUNT' },
        { label: 'Half-brother', value: 'NBRO' },
        { label: 'Half-sister', value: 'NSIS' },
    ],
    statusOptions: [
        { label: 'Partial', value: 'partial' },
        { label: 'Completed', value: 'completed' },
        { label: 'Entered in error', value: 'entered-in-error' },
        { label: 'Health unknown', value: 'health-unknown' },
    ],
}

export default content
