/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthzRouteImport } from './routes/_authz'
import { Route as AuthnRouteImport } from './routes/_authn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthzUserIdRouteImport } from './routes/_authz/user/$id'
import { Route as AuthzHealthConsumerIdRouteImport } from './routes/_authz/health-consumer/$id'

const AuthzSettingsLazyRouteImport = createFileRoute('/_authz/settings')()
const AuthzDashboardLazyRouteImport = createFileRoute('/_authz/dashboard')()
const AuthnSignUpLazyRouteImport = createFileRoute('/_authn/sign-up')()
const AuthnSignInLazyRouteImport = createFileRoute('/_authn/sign-in')()
const AuthnCheckEmailLazyRouteImport = createFileRoute('/_authn/check-email')()
const AuthzUserStadisticsLazyRouteImport = createFileRoute(
  '/_authz/user/stadistics',
)()
const AuthzUserListLazyRouteImport = createFileRoute('/_authz/user/list')()
const AuthzUserAddLazyRouteImport = createFileRoute('/_authz/user/add')()
const AuthzHealthConsumerStadisticsLazyRouteImport = createFileRoute(
  '/_authz/health-consumer/stadistics',
)()
const AuthzHealthConsumerListLazyRouteImport = createFileRoute(
  '/_authz/health-consumer/list',
)()
const AuthzHealthConsumerAddLazyRouteImport = createFileRoute(
  '/_authz/health-consumer/add',
)()

const AuthzRoute = AuthzRouteImport.update({
  id: '/_authz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthnRoute = AuthnRouteImport.update({
  id: '/_authn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthzSettingsLazyRoute = AuthzSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthzRoute,
} as any).lazy(() =>
  import('./routes/_authz/settings.lazy').then((d) => d.Route),
)
const AuthzDashboardLazyRoute = AuthzDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthzRoute,
} as any).lazy(() =>
  import('./routes/_authz/dashboard.lazy').then((d) => d.Route),
)
const AuthnSignUpLazyRoute = AuthnSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthnRoute,
} as any).lazy(() =>
  import('./routes/_authn/sign-up.lazy').then((d) => d.Route),
)
const AuthnSignInLazyRoute = AuthnSignInLazyRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthnRoute,
} as any).lazy(() =>
  import('./routes/_authn/sign-in.lazy').then((d) => d.Route),
)
const AuthnCheckEmailLazyRoute = AuthnCheckEmailLazyRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthnRoute,
} as any).lazy(() =>
  import('./routes/_authn/check-email.lazy').then((d) => d.Route),
)
const AuthzUserStadisticsLazyRoute = AuthzUserStadisticsLazyRouteImport.update({
  id: '/user/stadistics',
  path: '/user/stadistics',
  getParentRoute: () => AuthzRoute,
} as any).lazy(() =>
  import('./routes/_authz/user/stadistics.lazy').then((d) => d.Route),
)
const AuthzUserListLazyRoute = AuthzUserListLazyRouteImport.update({
  id: '/user/list',
  path: '/user/list',
  getParentRoute: () => AuthzRoute,
} as any).lazy(() =>
  import('./routes/_authz/user/list.lazy').then((d) => d.Route),
)
const AuthzUserAddLazyRoute = AuthzUserAddLazyRouteImport.update({
  id: '/user/add',
  path: '/user/add',
  getParentRoute: () => AuthzRoute,
} as any).lazy(() =>
  import('./routes/_authz/user/add.lazy').then((d) => d.Route),
)
const AuthzHealthConsumerStadisticsLazyRoute =
  AuthzHealthConsumerStadisticsLazyRouteImport.update({
    id: '/health-consumer/stadistics',
    path: '/health-consumer/stadistics',
    getParentRoute: () => AuthzRoute,
  } as any).lazy(() =>
    import('./routes/_authz/health-consumer/stadistics.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthzHealthConsumerListLazyRoute =
  AuthzHealthConsumerListLazyRouteImport.update({
    id: '/health-consumer/list',
    path: '/health-consumer/list',
    getParentRoute: () => AuthzRoute,
  } as any).lazy(() =>
    import('./routes/_authz/health-consumer/list.lazy').then((d) => d.Route),
  )
const AuthzHealthConsumerAddLazyRoute =
  AuthzHealthConsumerAddLazyRouteImport.update({
    id: '/health-consumer/add',
    path: '/health-consumer/add',
    getParentRoute: () => AuthzRoute,
  } as any).lazy(() =>
    import('./routes/_authz/health-consumer/add.lazy').then((d) => d.Route),
  )
const AuthzUserIdRoute = AuthzUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AuthzRoute,
} as any)
const AuthzHealthConsumerIdRoute = AuthzHealthConsumerIdRouteImport.update({
  id: '/health-consumer/$id',
  path: '/health-consumer/$id',
  getParentRoute: () => AuthzRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof AuthnCheckEmailLazyRoute
  '/sign-in': typeof AuthnSignInLazyRoute
  '/sign-up': typeof AuthnSignUpLazyRoute
  '/dashboard': typeof AuthzDashboardLazyRoute
  '/settings': typeof AuthzSettingsLazyRoute
  '/health-consumer/$id': typeof AuthzHealthConsumerIdRoute
  '/user/$id': typeof AuthzUserIdRoute
  '/health-consumer/add': typeof AuthzHealthConsumerAddLazyRoute
  '/health-consumer/list': typeof AuthzHealthConsumerListLazyRoute
  '/health-consumer/stadistics': typeof AuthzHealthConsumerStadisticsLazyRoute
  '/user/add': typeof AuthzUserAddLazyRoute
  '/user/list': typeof AuthzUserListLazyRoute
  '/user/stadistics': typeof AuthzUserStadisticsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof AuthnCheckEmailLazyRoute
  '/sign-in': typeof AuthnSignInLazyRoute
  '/sign-up': typeof AuthnSignUpLazyRoute
  '/dashboard': typeof AuthzDashboardLazyRoute
  '/settings': typeof AuthzSettingsLazyRoute
  '/health-consumer/$id': typeof AuthzHealthConsumerIdRoute
  '/user/$id': typeof AuthzUserIdRoute
  '/health-consumer/add': typeof AuthzHealthConsumerAddLazyRoute
  '/health-consumer/list': typeof AuthzHealthConsumerListLazyRoute
  '/health-consumer/stadistics': typeof AuthzHealthConsumerStadisticsLazyRoute
  '/user/add': typeof AuthzUserAddLazyRoute
  '/user/list': typeof AuthzUserListLazyRoute
  '/user/stadistics': typeof AuthzUserStadisticsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authn': typeof AuthnRouteWithChildren
  '/_authz': typeof AuthzRouteWithChildren
  '/_authn/check-email': typeof AuthnCheckEmailLazyRoute
  '/_authn/sign-in': typeof AuthnSignInLazyRoute
  '/_authn/sign-up': typeof AuthnSignUpLazyRoute
  '/_authz/dashboard': typeof AuthzDashboardLazyRoute
  '/_authz/settings': typeof AuthzSettingsLazyRoute
  '/_authz/health-consumer/$id': typeof AuthzHealthConsumerIdRoute
  '/_authz/user/$id': typeof AuthzUserIdRoute
  '/_authz/health-consumer/add': typeof AuthzHealthConsumerAddLazyRoute
  '/_authz/health-consumer/list': typeof AuthzHealthConsumerListLazyRoute
  '/_authz/health-consumer/stadistics': typeof AuthzHealthConsumerStadisticsLazyRoute
  '/_authz/user/add': typeof AuthzUserAddLazyRoute
  '/_authz/user/list': typeof AuthzUserListLazyRoute
  '/_authz/user/stadistics': typeof AuthzUserStadisticsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/health-consumer/$id'
    | '/user/$id'
    | '/health-consumer/add'
    | '/health-consumer/list'
    | '/health-consumer/stadistics'
    | '/user/add'
    | '/user/list'
    | '/user/stadistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/health-consumer/$id'
    | '/user/$id'
    | '/health-consumer/add'
    | '/health-consumer/list'
    | '/health-consumer/stadistics'
    | '/user/add'
    | '/user/list'
    | '/user/stadistics'
  id:
    | '__root__'
    | '/'
    | '/_authn'
    | '/_authz'
    | '/_authn/check-email'
    | '/_authn/sign-in'
    | '/_authn/sign-up'
    | '/_authz/dashboard'
    | '/_authz/settings'
    | '/_authz/health-consumer/$id'
    | '/_authz/user/$id'
    | '/_authz/health-consumer/add'
    | '/_authz/health-consumer/list'
    | '/_authz/health-consumer/stadistics'
    | '/_authz/user/add'
    | '/_authz/user/list'
    | '/_authz/user/stadistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthnRoute: typeof AuthnRouteWithChildren
  AuthzRoute: typeof AuthzRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authz': {
      id: '/_authz'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authn': {
      id: '/_authn'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authz/settings': {
      id: '/_authz/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthzSettingsLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/dashboard': {
      id: '/_authz/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthzDashboardLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authn/sign-up': {
      id: '/_authn/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthnSignUpLazyRouteImport
      parentRoute: typeof AuthnRoute
    }
    '/_authn/sign-in': {
      id: '/_authn/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthnSignInLazyRouteImport
      parentRoute: typeof AuthnRoute
    }
    '/_authn/check-email': {
      id: '/_authn/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthnCheckEmailLazyRouteImport
      parentRoute: typeof AuthnRoute
    }
    '/_authz/user/stadistics': {
      id: '/_authz/user/stadistics'
      path: '/user/stadistics'
      fullPath: '/user/stadistics'
      preLoaderRoute: typeof AuthzUserStadisticsLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/user/list': {
      id: '/_authz/user/list'
      path: '/user/list'
      fullPath: '/user/list'
      preLoaderRoute: typeof AuthzUserListLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/user/add': {
      id: '/_authz/user/add'
      path: '/user/add'
      fullPath: '/user/add'
      preLoaderRoute: typeof AuthzUserAddLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/health-consumer/stadistics': {
      id: '/_authz/health-consumer/stadistics'
      path: '/health-consumer/stadistics'
      fullPath: '/health-consumer/stadistics'
      preLoaderRoute: typeof AuthzHealthConsumerStadisticsLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/health-consumer/list': {
      id: '/_authz/health-consumer/list'
      path: '/health-consumer/list'
      fullPath: '/health-consumer/list'
      preLoaderRoute: typeof AuthzHealthConsumerListLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/health-consumer/add': {
      id: '/_authz/health-consumer/add'
      path: '/health-consumer/add'
      fullPath: '/health-consumer/add'
      preLoaderRoute: typeof AuthzHealthConsumerAddLazyRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/user/$id': {
      id: '/_authz/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof AuthzUserIdRouteImport
      parentRoute: typeof AuthzRoute
    }
    '/_authz/health-consumer/$id': {
      id: '/_authz/health-consumer/$id'
      path: '/health-consumer/$id'
      fullPath: '/health-consumer/$id'
      preLoaderRoute: typeof AuthzHealthConsumerIdRouteImport
      parentRoute: typeof AuthzRoute
    }
  }
}

interface AuthnRouteChildren {
  AuthnCheckEmailLazyRoute: typeof AuthnCheckEmailLazyRoute
  AuthnSignInLazyRoute: typeof AuthnSignInLazyRoute
  AuthnSignUpLazyRoute: typeof AuthnSignUpLazyRoute
}

const AuthnRouteChildren: AuthnRouteChildren = {
  AuthnCheckEmailLazyRoute: AuthnCheckEmailLazyRoute,
  AuthnSignInLazyRoute: AuthnSignInLazyRoute,
  AuthnSignUpLazyRoute: AuthnSignUpLazyRoute,
}

const AuthnRouteWithChildren = AuthnRoute._addFileChildren(AuthnRouteChildren)

interface AuthzRouteChildren {
  AuthzDashboardLazyRoute: typeof AuthzDashboardLazyRoute
  AuthzSettingsLazyRoute: typeof AuthzSettingsLazyRoute
  AuthzHealthConsumerIdRoute: typeof AuthzHealthConsumerIdRoute
  AuthzUserIdRoute: typeof AuthzUserIdRoute
  AuthzHealthConsumerAddLazyRoute: typeof AuthzHealthConsumerAddLazyRoute
  AuthzHealthConsumerListLazyRoute: typeof AuthzHealthConsumerListLazyRoute
  AuthzHealthConsumerStadisticsLazyRoute: typeof AuthzHealthConsumerStadisticsLazyRoute
  AuthzUserAddLazyRoute: typeof AuthzUserAddLazyRoute
  AuthzUserListLazyRoute: typeof AuthzUserListLazyRoute
  AuthzUserStadisticsLazyRoute: typeof AuthzUserStadisticsLazyRoute
}

const AuthzRouteChildren: AuthzRouteChildren = {
  AuthzDashboardLazyRoute: AuthzDashboardLazyRoute,
  AuthzSettingsLazyRoute: AuthzSettingsLazyRoute,
  AuthzHealthConsumerIdRoute: AuthzHealthConsumerIdRoute,
  AuthzUserIdRoute: AuthzUserIdRoute,
  AuthzHealthConsumerAddLazyRoute: AuthzHealthConsumerAddLazyRoute,
  AuthzHealthConsumerListLazyRoute: AuthzHealthConsumerListLazyRoute,
  AuthzHealthConsumerStadisticsLazyRoute:
    AuthzHealthConsumerStadisticsLazyRoute,
  AuthzUserAddLazyRoute: AuthzUserAddLazyRoute,
  AuthzUserListLazyRoute: AuthzUserListLazyRoute,
  AuthzUserStadisticsLazyRoute: AuthzUserStadisticsLazyRoute,
}

const AuthzRouteWithChildren = AuthzRoute._addFileChildren(AuthzRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthnRoute: AuthnRouteWithChildren,
  AuthzRoute: AuthzRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
