export const contentEN = {
    title: 'Register Appointment Form',
    errorPatientRequired: 'Please use a valid email address',
    errorPhysicianRequired: 'The email address is required',
    errorInvalidTime: 'Invalid time format',
    labelPatient: 'Patient',
    labelPhysician: 'Physician',
    labelDate: 'Appointment date',
    labelTime: 'Time',
    labelNotes: 'Notes',
    placeholderPatient: 'Select patient by name',
    placeholderPhysician: 'Select physician by name',
    textNoCommandPatientFound: 'No patient found',
    textNoCommandPhysicianFound: 'No physician found',
    textToastSuccess: 'Appointment add successfully',
    textToastFail: 'Failed to add appointment',
    textButtonSend: 'Add appointment',
    textButtonSending: 'Sending',
}

export type AddNewAppointmentContent = typeof contentEN

export const contentES: AddNewAppointmentContent = {
    title: 'Formulario de registro de cita',
    errorPatientRequired: 'Por favor, use una dirección de correo electrónico válida',
    errorPhysicianRequired: 'La dirección de correo electrónico es obligatoria',
    errorInvalidTime: 'Formato de hora no válido',
    labelPatient: 'Paciente',
    labelPhysician: 'Médico',
    labelDate: 'Fecha de la cita',
    labelTime: 'Hora',
    labelNotes: 'Notas',
    placeholderPatient: 'Seleccionar paciente por nombre',
    placeholderPhysician: 'Seleccionar médico por nombre',
    textNoCommandPatientFound: 'No se encontró ningún paciente',
    textNoCommandPhysicianFound: 'No se encontró ningún médico',
    textToastSuccess: 'Cita añadida correctamente',
    textToastFail: 'Error al añadir la cita',
    textButtonSend: 'Añadir cita',
    textButtonSending: 'Enviando',
}
